### ISSUE TITLE
Failed to write Service.yml

### ISSUE THREAD

**Issue by przbadu** [cloud66/starter#32]
I am running `starter` for `rails 5.0.0.rc1` and `Dockerfile` seems to generate without error, but I get error when writing `service.yml`.

    Failed to write service.yml due to: template: service.yml.template:29:6: executing "service.yml.template" at <.Name>: can't evaluate field Name in type string

`service.yml.template:29:6` has this code:

`  - {{.Name}}`

Am I missing anything in `config/database.yml` file? Please suggest

**Comment by przbadu** [comment]
FYI: I am using latest version of `starter` i.e `1.0.2`.

I downloaded `1.0.0` version and got this error:

    Failed to write Dockerfile due to: open ~/Downloads/starter_1.0.0_darwin_amd64/templates/dockerfiles/ruby.dockerfile.template: no such file or directory
    Failed to write service.yml due to: open ~/Downloads/starter_1.0.0_darwin_amd64/templates/service-yml/service.yml.template: no such file or directory

**Comment by przbadu** [comment]
I downloaded `1.0.1` version and got same problem as `1.0.2`:

    Failed to write service.yml due to: template: service.yml.template:29:6: executing "service.yml.template" at <.Name>: can't evaluate field Name in type string

**Comment by sigfrid** [comment]
I have just installed `1.0.3` via `Homebrew` and I get the same error while running `starter` on a Rails 5.0.0.1

Am I missing anything?

Thanks

**Comment by kamerblauwlicht** [comment]
looks like the templates are not updated correctly. 
can you remove /.starter folder and run starter again, this will download the latest templates.

**Comment by sigfrid** [comment]
@kamerblauwlicht thanks for your reply. 
Where am I suppose to find the folder. The formula folder contains only the bin directory.

FYI I'm running 1.0.2 and not 1.0.3

**Comment by jonsgreen** [comment]
I have run into the same issue from a fresh brew install of starter.

**Comment by khash** [comment]
@jonsgreen do you have the same issue with the one in the Releases folder?
