### ISSUE TITLE
Failed to write docker-compose.yml

### ISSUE THREAD

**Issue by przbadu** [cloud66/starter#33]
I am using latest version of starter `1.0.2` and getting this error:

    Failed to write docker-compose.yml due to: template: docker-compose.yml.template:19:6: executing "docker-compose.yml.template" at <.Name>: can't evaluate field Name in type string

**Comment by przbadu** [comment]
Related isues: https://github.com/cloud66/starter/issues/32

**Comment by przbadu** [comment]
Looks like database section has an issue

**Comment by kamerblauwlicht** [comment]
please use version 1.0.3

**Comment by przbadu** [comment]
@kamerblauwlicht: thank you for your reply, 

I tried https://codeload.github.com/cloud66/c66starter/zip/1.0.3 which is not working, also tried to download from https://app.cloud66.com/starter for Mac OSx, looks like both url are not working.

can you also let me know where can I find v1.0.3 starter kit?

**Comment by przbadu** [comment]
Well, I think I can download directlly from https://github.com/cloud66/starter/releases

Thanks @kamerblauwlicht once again

**Comment by kamerblauwlicht** [comment]
@przbadu I added a ticket to our system to update the link @ https://app.cloud66.com/starter  Thanks for letting us know. 

starter 1.0.3: https://github.com/cloud66/starter/releases/tag/1.0.3

**Comment by benwigley** [comment]
@kamerblauwlicht I am also getting this issue. I'm trying to follow along with this article http://blog.cloud66.com/migrating-a-rails-application-to-docker/

None of the files found at https://github.com/cloud66/starter/releases/tag/1.0.3 did anything for me, is there a special way to use them? I tried opening them in terminal. Thanks.

**Comment by kamerblauwlicht** [comment]
hi @benwigley, which operating system are you using. Make sure you get the right one. For Mac use: [https://github.com/cloud66/starter/releases/download/1.0.3/starter_darwin_amd64](https://github.com/cloud66/starter/releases/download/1.0.3/starter_darwin_amd64). For Windows use: [https://github.com/cloud66/starter/releases/download/1.0.3/starter_windows_amd64.exe](https://github.com/cloud66/starter/releases/download/1.0.3/starter_windows_amd64.exe)

**Comment by kamerblauwlicht** [comment]
@benwigley if you download for Mac, probably the executable doesn't have the executable flag. Please run:  chmod a+x starter_darwin_amd64

**Comment by benwigley** [comment]
Thanks @kamerblauwlicht - permissions was the issue.
