### ISSUE TITLE
Failed to write service.yml

### ISSUE THREAD

**Issue by olimart** [cloud66/starter#44]
With c66starter-1.0.2
`starter -overwrite dockerfile,service,docker-compose` raises

``` 
Failed to write service.yml due to: template: service.yml.template:29:6: executing
"service.yml.template" at <.Name>: can't evaluate field Name in type string
```

and docker-compose does not get created.

**Comment by kamerblauwlicht** [comment]
Hi @olimart. you need to upgrade to starter-1.1.0 to work with the new templates. please upgrade to 1.1.0 thanks.

**Comment by olimart** [comment]
Thanks @kamerblauwlicht 

It seems that `1.1.0` is not available from homebrew. Can you please explain how to upgrade on Mac or upgrade homebrew. Thanks

**Comment by unRARed** [comment]
Is there a solution yet for Homebrew? The homepage of http://www.startwithdocker.com/ still recommends it.

```sh
brew tap cloud66/tap
brew install c66starter
cd /my/rails/repo
starter
```

Output: 

```sh
... 
----> Writing service.yml...
Failed to write service.yml due to: template: service.yml.template:29:6: executing "service.yml.template" at <.Name>: can't evaluate field Name in type string
```

**Comment by unRARed** [comment]
Nevermind, curl install from README worked: `curl -sSL https://raw.githubusercontent.com/cloud66/starter/master/install.sh | bash`

website should probably still be updated to reflect...

**Comment by khash** [comment]
There shouldn't be any references to brew on the site

**Comment by r4nd3l** [comment]
Hi there!

I also have a similar issue:

`----> Found Script: npm start
 ----> Writing Dockerfile...
 ----> Writing service.yml...
 Failed to write service.yml due to: template: service.yml.template:21:9: executing "service.yml.template"`
 
 Using the version of 1.4.3
 
 Any fix for that? Would very appreciate
