### ISSUE TITLE
Figure out best way to add production web server

### ISSUE THREAD

**Issue by pkallberg** [cloud66/starter#9]
Current builds will use Webrick, which is extremely slow. 

Adding `thin` to Gemfile is one option, but requires touching users' code... I tried adding `RUN bundle exec gem install thin` to Dockerfile after `bundle install` but it still uses Webrick.

Using Passenger probably isn't great as it requires Nginx in the container as well.

**Comment by remyferre** [comment]
It has been decided not to touch user's code, i.e it is up to the user to define the production server. A warning is displayed if there is no Procfile to define the web service command.
